# Chart Releaser configuration
# Documentation: https://github.com/helm/chart-releaser

# Repository settings
owner: favish
git-repo: bitnami-resources

# Release settings
release-name-template: "{{ .Name }}-{{ .Version }}"
commit-username: github-actions[bot]
commit-email: 41898282+github-actions[bot]@users.noreply.github.com

# Chart settings
charts-repo: https://favish.github.io/bitnami-resources
index-path: .cr-index/index.yaml

# Package settings
package-path: .cr-release-packages
pages-branch: gh-pages
pages-index-path: index.yaml

# Generation settings
generate-release-notes: true
make-release-latest: true

# Skip settings
skip-dependencies: false
skip-existing: true