name: Build Docker Images

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      redis: ${{ steps.changes.outputs.redis }}
      discourse: ${{ steps.changes.outputs.discourse }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            redis:
              - 'containers/redis/**'
            discourse:
              - 'containers/discourse/**'

  build-redis:
    needs: detect-changes
    if: needs.detect-changes.outputs.redis == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['8.2']
        variant: ['debian-12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/redis
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}-{{sha}}
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}-r${{ github.run_number }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Redis image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: containers/redis/${{ matrix.version }}/${{ matrix.variant }}
          file: containers/redis/${{ matrix.version }}/${{ matrix.variant }}/Dockerfile
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            BUILD_NUMBER=${{ github.run_number }}
            BUILD_ID=${{ github.run_id }}
            GITHUB_REF=${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  build-discourse:
    needs: detect-changes
    if: needs.detect-changes.outputs.discourse == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ['3']
        variant: ['debian-12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:latest
          buildkitd-config-inline: |
            [worker.oci]
              max-parallelism = 2
            [worker.containerd]
              max-parallelism = 2

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/discourse
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}-{{sha}}
            type=raw,value=${{ matrix.version }}-${{ matrix.variant }}-r${{ github.run_number }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Discourse image
        id: build
        uses: docker/build-push-action@v5
        env:
          # Optimize parallel builds for 8-core runner
          MAKEFLAGS: "-j8"
        with:
          context: containers/discourse/${{ matrix.version }}/${{ matrix.variant }}
          file: containers/discourse/${{ matrix.version }}/${{ matrix.variant }}/Dockerfile
          target: prod
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            BUILD_NUMBER=${{ github.run_number }}
            BUILD_ID=${{ github.run_id }}
            GITHUB_REF=${{ github.ref_name }}
            MAKEFLAGS=-j8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  scan-redis:
    needs: build-redis
    if: needs.build-redis.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    strategy:
      matrix:
        version: ['8.2']
        variant: ['debian-12']
    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner for Redis
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.OWNER }}/redis:${{ matrix.version }}-${{ matrix.variant }}
          format: 'sarif'
          output: 'trivy-results-redis-${{ matrix.version }}-${{ matrix.variant }}.sarif'
          timeout: '10m'
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-redis-${{ matrix.version }}-${{ matrix.variant }}.sarif'

  scan-discourse:
    needs: build-discourse
    if: needs.build-discourse.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    strategy:
      matrix:
        version: ['3']
        variant: ['debian-12']
    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner for Discourse
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.OWNER }}/discourse:${{ matrix.version }}-${{ matrix.variant }}
          format: 'sarif'
          output: 'trivy-results-discourse-${{ matrix.version }}-${{ matrix.variant }}.sarif'
          timeout: '15m'
          skip-dirs: '/opt/discourse/node_modules,/opt/discourse/vendor/bundle'
          skip-files: '*.bin,*.so,*.dylib'
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results-discourse-${{ matrix.version }}-${{ matrix.variant }}.sarif'
